<?php
/**
 * @property CI_DB_active_record $db
 * @property CI_DB_forge $dbforge
 * @property CI_Benchmark $benchmark
 * @property CI_Calendar $calendar
 * @property CI_Cart $cart
 * @property CI_Config $config
 * @property CI_Controller $controller
 * @property CI_Email $email
 * @property CI_Encrypt $encrypt
 * @property CI_Exceptions $exceptions
 * @property CI_Form_validation $form_validation
 * @property CI_Ftp $ftp
 * @property CI_Hooks $hooks
 * @property CI_Image_lib $image_lib
 * @property CI_Input $input
 * @property CI_Language $language
 * @property CI_Loader $load
 * @property CI_Log $log
 * @property CI_Model $model
 * @property CI_Output $output
 * @property CI_Pagination $pagination
 * @property CI_Parser $parser
 * @property CI_Profiler $profiler
 * @property CI_Router $router
 * @property CI_Session $session
 * @property CI_Sha1 $sha1
 * @property CI_Table $table
 * @property CI_Trackback $trackback
 * @property CI_Typography $typography
 * @property CI_Unit_test $unit_test
 * @property CI_Upload $upload
 * @property CI_URI $uri
 * @property CI_User_agent $user_agent
 * @property CI_Validation $validation
 * @property CI_Xmlrpc $xmlrpc
 * @property CI_Xmlrpcs $xmlrpcs
 * @property CI_Zip $zip
 *
 * @property SCompanyInfo $sCompanyInfo
 * @property SDealInfo $sDealInfo
 * @property SUserInfo $sUserInfo
 * @property SMyPage $sMyPage
 * @property SPtypeBdBase $sPtypeBdBase
 * @property SPtypeBdCate $sPtypeBdCate
 * @property SPtypeBdNotice $sPtypeBdNotice
 * @property SPtypeBdQNA $sPtypeBdQNA
 * @property SPtypeExcelUpDown $sPtypeExcelUpDown
 * @property SPtypeFileUpDown $sPtypeFileUpDown
 * @property SPtypeMail $sPtypeMail
 * @property SPtypeSmartEditor $sPtypeSmartEditor
 * @property SPtypeZipCode $sPtypeZipCode
 * @property SLogin $sLogin
 * @property SGroupPowerManager $sGroupPowerManager
 * @property SOrgManager $sOrgManager
 * @property SOrgPowerManager $sOrgPowerManager
 * @property SPersonalPowerManager $sPersonalPowerManager
 * @property SEditor $sEditor
 * @property SGroupware $sGroupware
 * @property SPopSearchUser $sPopSearchUser
 * @property SSellingSearch $sSellingSearch
 * @property SUserProfile $sUserProfile
 * @property SConfPaperMng $sConfPaperMng
 * @property SCopeSrcAdmin $sCopeSrcAdmin
 * @property SCopeSrcExcel $sCopeSrcExcel
 * @property SCopeSrcMgr $sCopeSrcMgr
 * @property SCopeSrcNotice $sCopeSrcNotice
 * @property SCopeSrcStats $sCopeSrcStats
 * @property SCopeSrcUser $sCopeSrcUser
 * @property SMigrationDetail $sMigrationDetail
 * @property SMigrationList $sMigrationList
 * @property SMigrationRegist $sMigrationRegist
 * @property STaskCondition $sTaskCondition
 * @property SToDoList $sToDoList
 * @property SNoticeDetail $sNoticeDetail
 * @property SNoticeFile $sNoticeFile
 * @property SNoticeList $sNoticeList
 * @property SNoticeRegist $sNoticeRegist
 * @property SPartnerChartDetail $sPartnerChartDetail
 * @property SPartnerChartList $sPartnerChartList
 * @property SLoginSession $sLoginSession
 * @property STransferCommon $sTransferCommon
 * @property STransferDetail $sTransferDetail
 * @property STransferReceive $sTransferReceive
 * @property STransferSendFile $sTransferSendFile
 * @property STransferSendList $sTransferSendList
 * @property STest $sTest
 * @property MgrSalesProfile $mgrSalesProfile
 * @property MgrContentsInfo $mgrContentsInfo
 * @property MgrMktInfo $mgrMktInfo
 * @property MgrSafetyInfo $mgrSafetyInfo
 * @property MgrCompanyInfo $mgrCompanyInfo
 * @property MgrDealInfo $mgrDealInfo
 * @property MgrUserInfo $mgrUserInfo
 * @property MgrFile $mgrFile
 * @property MgrLogin $mgrLogin
 * @property MgrEditor $mgrEditor
 * @property MgrEmail $mgrEmail
 * @property MgrOrg $mgrOrg
 * @property MgrPower $mgrPower
 * @property MgrTest $mgrTest
 * @property MgrZipDownload $mgrZipDownload
 * @property MgrComment $mgrComment
 *
 */

class CI_Controller {};


/**
 * @property CI_DB_active_record $db
 * @property CI_DB_forge $dbforge
 * @property CI_Benchmark $benchmark
 * @property CI_Calendar $calendar
 * @property CI_Cart $cart
 * @property CI_Config $config
 * @property CI_Controller $controller
 * @property CI_Email $email
 * @property CI_Encrypt $encrypt
 * @property CI_Exceptions $exceptions
 * @property CI_Form_validation $form_validation
 * @property CI_Ftp $ftp
 * @property CI_Hooks $hooks
 * @property CI_Image_lib $image_lib
 * @property CI_Input $input
 * @property CI_Language $language
 * @property CI_Loader $load
 * @property CI_Log $log
 * @property CI_Model $model
 * @property CI_Output $output
 * @property CI_Pagination $pagination
 * @property CI_Parser $parser
 * @property CI_Profiler $profiler
 * @property CI_Router $router
 * @property CI_Session $session
 * @property CI_Sha1 $sha1
 * @property CI_Table $table
 * @property CI_Trackback $trackback
 * @property CI_Typography $typography
 * @property CI_Unit_test $unit_test
 * @property CI_Upload $upload
 * @property CI_URI $uri
 * @property CI_User_agent $user_agent
 * @property CI_Validation $validation
 * @property CI_Xmlrpc $xmlrpc
 * @property CI_Xmlrpcs $xmlrpcs
 * @property CI_Zip $zip
 *
 * @property SCompanyInfo $sCompanyInfo
 * @property SDealInfo $sDealInfo
 * @property SUserInfo $sUserInfo
 * @property SMyPage $sMyPage
 * @property SPtypeBdBase $sPtypeBdBase
 * @property SPtypeBdCate $sPtypeBdCate
 * @property SPtypeBdNotice $sPtypeBdNotice
 * @property SPtypeBdQNA $sPtypeBdQNA
 * @property SPtypeExcelUpDown $sPtypeExcelUpDown
 * @property SPtypeFileUpDown $sPtypeFileUpDown
 * @property SPtypeMail $sPtypeMail
 * @property SPtypeSmartEditor $sPtypeSmartEditor
 * @property SPtypeZipCode $sPtypeZipCode
 * @property SLogin $sLogin
 * @property SGroupPowerManager $sGroupPowerManager
 * @property SOrgManager $sOrgManager
 * @property SOrgPowerManager $sOrgPowerManager
 * @property SPersonalPowerManager $sPersonalPowerManager
 * @property SEditor $sEditor
 * @property SGroupware $sGroupware
 * @property SPopSearchUser $sPopSearchUser
 * @property SSellingSearch $sSellingSearch
 * @property SUserProfile $sUserProfile
 * @property SConfPaperMng $sConfPaperMng
 * @property SCopeSrcAdmin $sCopeSrcAdmin
 * @property SCopeSrcExcel $sCopeSrcExcel
 * @property SCopeSrcMgr $sCopeSrcMgr
 * @property SCopeSrcNotice $sCopeSrcNotice
 * @property SCopeSrcStats $sCopeSrcStats
 * @property SCopeSrcUser $sCopeSrcUser
 * @property SMigrationDetail $sMigrationDetail
 * @property SMigrationList $sMigrationList
 * @property SMigrationRegist $sMigrationRegist
 * @property STaskCondition $sTaskCondition
 * @property SToDoList $sToDoList
 * @property SNoticeDetail $sNoticeDetail
 * @property SNoticeFile $sNoticeFile
 * @property SNoticeList $sNoticeList
 * @property SNoticeRegist $sNoticeRegist
 * @property SPartnerChartDetail $sPartnerChartDetail
 * @property SPartnerChartList $sPartnerChartList
 * @property SLoginSession $sLoginSession
 * @property STransferCommon $sTransferCommon
 * @property STransferDetail $sTransferDetail
 * @property STransferReceive $sTransferReceive
 * @property STransferSendFile $sTransferSendFile
 * @property STransferSendList $sTransferSendList
 * @property STest $sTest
 * @property MPDF $mPDF
 * @property MBbsNotice $mBbsNotice
 * @property MBbsNoticeUpfile $mBbsNoticeUpfile
 * @property MBbsNoticeWyupfile $mBbsNoticeWyupfile
 * @property MChartCompanyCmt $mChartCompanyCmt
 * @property MChartCompanyHistory $mChartCompanyHistory
 * @property MConfAttendee $mConfAttendee
 * @property MConfPaper $mConfPaper
 * @property MConfPaperArticle $mConfPaperArticle
 * @property MConfPaperCmt $mConfPaperCmt
 * @property MConfPaperWy $mConfPaperWy
 * @property MMigrationDetails $mMigrationDetails
 * @property MMigrationRequest $mMigrationRequest
 * @property MOrganize $mOrganize
 * @property MPwrAuthorityMap $mPwrAuthorityMap
 * @property MPwrCode $mPwrCode
 * @property MPwrGroup $mPwrGroup
 * @property MPwrGroupMap $mPwrGroupMap
 * @property MRespNotice $mRespNotice
 * @property MRespProc $mRespProc
 * @property MRespSrcData1 $mRespSrcData1
 * @property MRespSrcData2 $mRespSrcData2
 * @property MRespSrcReport $mRespSrcReport
 * @property MTaskReceive $mTaskReceive
 * @property MTaskTransfer $mTaskTransfer
 * @property MTaskTransferUpfile $mTaskTransferUpfile
 * @property MToDoList $mToDoList
 * @property MUserProfile $mUserProfile
 * @property MComment $mComment
 * @property MOrg $mOrg
 * @property MAdmin $mAdmin
 * @property MPtypeBdbase $mPtypeBdbase
 * @property MPtypeBdbaseCmt $mPtypeBdbaseCmt
 * @property MPtypeBdCate $mPtypeBdCate
 * @property MPtypeBdNotice $mPtypeBdNotice
 * @property MPtypeBdNoticeEditor $mPtypeBdNoticeEditor
 * @property MPtypeBdnoticeUpfile $mPtypeBdnoticeUpfile
 * @property MPtypeBdqna $mPtypeBdqna
 * @property MPtypeBdqnaCmt $mPtypeBdqnaCmt
 * @property MPtypeBdqnaEditor $mPtypeBdqnaEditor
 * @property MPtypeBdqnaUpfile $mPtypeBdqnaUpfile
 * @property MPtypeExcelUpdown $mPtypeExcelUpdown
 * @property MPtypeFileUpDown $mPtypeFileUpDown
 * @property MPtypeMailSend $mPtypeMailSend
 * @property MPtypeSmartEditor $mPtypeSmartEditor
 * @property MPtypeZipCode $mPtypeZipCode
 * @property MPtypeZipStreet $mPtypeZipStreet
 * @property MgrSalesProfile $mgrSalesProfile
 * @property MgrContentsInfo $mgrContentsInfo
 * @property MgrMktInfo $mgrMktInfo
 * @property MgrSafetyInfo $mgrSafetyInfo
 * @property MgrCompanyInfo $mgrCompanyInfo
 * @property MgrDealInfo $mgrDealInfo
 * @property MgrUserInfo $mgrUserInfo
 * @property MgrFile $mgrFile
 * @property MgrLogin $mgrLogin
 * @property MgrEditor $mgrEditor
 * @property MgrEmail $mgrEmail
 * @property MgrOrg $mgrOrg
 * @property MgrPower $mgrPower
 * @property MgrTest $mgrTest
 * @property MgrZipDownload $mgrZipDownload
 * @property MgrComment $mgrComment
 *
 */
class Service_app {};

/**
 * @property CI_DB_active_record $db
 * @property CI_DB_forge $dbforge
 * @property CI_Config $config
 * @property CI_Loader $load
 * @property CI_Session $session
 *
 * @property SCompanyInfo $sCompanyInfo
 * @property SDealInfo $sDealInfo
 * @property SUserInfo $sUserInfo
 * @property SMyPage $sMyPage
 * @property SPtypeBdBase $sPtypeBdBase
 * @property SPtypeBdCate $sPtypeBdCate
 * @property SPtypeBdNotice $sPtypeBdNotice
 * @property SPtypeBdQNA $sPtypeBdQNA
 * @property SPtypeExcelUpDown $sPtypeExcelUpDown
 * @property SPtypeFileUpDown $sPtypeFileUpDown
 * @property SPtypeMail $sPtypeMail
 * @property SPtypeSmartEditor $sPtypeSmartEditor
 * @property SPtypeZipCode $sPtypeZipCode
 * @property SLogin $sLogin
 * @property SGroupPowerManager $sGroupPowerManager
 * @property SOrgManager $sOrgManager
 * @property SOrgPowerManager $sOrgPowerManager
 * @property SPersonalPowerManager $sPersonalPowerManager
 * @property SEditor $sEditor
 * @property SGroupware $sGroupware
 * @property SPopSearchUser $sPopSearchUser
 * @property SSellingSearch $sSellingSearch
 * @property SUserProfile $sUserProfile
 * @property SConfPaperMng $sConfPaperMng
 * @property SCopeSrcAdmin $sCopeSrcAdmin
 * @property SCopeSrcExcel $sCopeSrcExcel
 * @property SCopeSrcMgr $sCopeSrcMgr
 * @property SCopeSrcNotice $sCopeSrcNotice
 * @property SCopeSrcStats $sCopeSrcStats
 * @property SCopeSrcUser $sCopeSrcUser
 * @property SMigrationDetail $sMigrationDetail
 * @property SMigrationList $sMigrationList
 * @property SMigrationRegist $sMigrationRegist
 * @property STaskCondition $sTaskCondition
 * @property SToDoList $sToDoList
 * @property SNoticeDetail $sNoticeDetail
 * @property SNoticeFile $sNoticeFile
 * @property SNoticeList $sNoticeList
 * @property SNoticeRegist $sNoticeRegist
 * @property SPartnerChartDetail $sPartnerChartDetail
 * @property SPartnerChartList $sPartnerChartList
 * @property SLoginSession $sLoginSession
 * @property STransferCommon $sTransferCommon
 * @property STransferDetail $sTransferDetail
 * @property STransferReceive $sTransferReceive
 * @property STransferSendFile $sTransferSendFile
 * @property STransferSendList $sTransferSendList
 * @property STest $sTest
 * @property MPDF $mPDF
 * @property MBbsNotice $mBbsNotice
 * @property MBbsNoticeUpfile $mBbsNoticeUpfile
 * @property MBbsNoticeWyupfile $mBbsNoticeWyupfile
 * @property MChartCompanyCmt $mChartCompanyCmt
 * @property MChartCompanyHistory $mChartCompanyHistory
 * @property MConfAttendee $mConfAttendee
 * @property MConfPaper $mConfPaper
 * @property MConfPaperArticle $mConfPaperArticle
 * @property MConfPaperCmt $mConfPaperCmt
 * @property MConfPaperWy $mConfPaperWy
 * @property MMigrationDetails $mMigrationDetails
 * @property MMigrationRequest $mMigrationRequest
 * @property MOrganize $mOrganize
 * @property MPwrAuthorityMap $mPwrAuthorityMap
 * @property MPwrCode $mPwrCode
 * @property MPwrGroup $mPwrGroup
 * @property MPwrGroupMap $mPwrGroupMap
 * @property MRespNotice $mRespNotice
 * @property MRespProc $mRespProc
 * @property MRespSrcData1 $mRespSrcData1
 * @property MRespSrcData2 $mRespSrcData2
 * @property MRespSrcReport $mRespSrcReport
 * @property MTaskReceive $mTaskReceive
 * @property MTaskTransfer $mTaskTransfer
 * @property MTaskTransferUpfile $mTaskTransferUpfile
 * @property MToDoList $mToDoList
 * @property MUserProfile $mUserProfile
 * @property MComment $mComment
 * @property MOrg $mOrg
 * @property MAdmin $mAdmin
 * @property MPtypeBdbase $mPtypeBdbase
 * @property MPtypeBdbaseCmt $mPtypeBdbaseCmt
 * @property MPtypeBdCate $mPtypeBdCate
 * @property MPtypeBdNotice $mPtypeBdNotice
 * @property MPtypeBdNoticeEditor $mPtypeBdNoticeEditor
 * @property MPtypeBdnoticeUpfile $mPtypeBdnoticeUpfile
 * @property MPtypeBdqna $mPtypeBdqna
 * @property MPtypeBdqnaCmt $mPtypeBdqnaCmt
 * @property MPtypeBdqnaEditor $mPtypeBdqnaEditor
 * @property MPtypeBdqnaUpfile $mPtypeBdqnaUpfile
 * @property MPtypeExcelUpdown $mPtypeExcelUpdown
 * @property MPtypeFileUpDown $mPtypeFileUpDown
 * @property MPtypeMailSend $mPtypeMailSend
 * @property MPtypeSmartEditor $mPtypeSmartEditor
 * @property MPtypeZipCode $mPtypeZipCode
 * @property MPtypeZipStreet $mPtypeZipStreet
 * @property MgrSalesProfile $mgrSalesProfile
 * @property MgrContentsInfo $mgrContentsInfo
 * @property MgrMktInfo $mgrMktInfo
 * @property MgrSafetyInfo $mgrSafetyInfo
 * @property MgrCompanyInfo $mgrCompanyInfo
 * @property MgrDealInfo $mgrDealInfo
 * @property MgrUserInfo $mgrUserInfo
 * @property MgrFile $mgrFile
 * @property MgrLogin $mgrLogin
 * @property MgrEditor $mgrEditor
 * @property MgrEmail $mgrEmail
 * @property MgrOrg $mgrOrg
 * @property MgrPower $mgrPower
 * @property MgrTest $mgrTest
 * @property MgrZipDownload $mgrZipDownload
 * @property MgrComment $mgrComment
 *
 */

class CI_Model {};